package spring.petstore.core.model;

// Generated Jul 30, 2007 12:22:19 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	// Fields    

	private long id;
	private String name;
	private Set items = new HashSet(0);

	// Constructors

	/** default constructor */
	public Category() {
	}

	/** minimal constructor */
	public Category(long id) {
		this.id = id;
	}

	/** full constructor */
	public Category(long id, String name, Set items) {
		this.id = id;
		this.name = name;
		this.items = items;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
