insert into category (ID, NAME) values(1,'Cats');
insert into category (ID, NAME) values(2,'Dogs');
insert into category (ID, NAME) values(3,'Reptiles');

insert into item (CATEGORY_ID_FK, ID, NAME, DESCRIPTION) values('1','11','Siberian','The Siberian is a long haired breed of cat. The Siberian cat breed is recognized by most cat organizations, which accept Siberians of any color (including color points) for competition. This includes recognition in the major cat registries such as TICA and Cat Fancier`s Association (CFA), as well as acceptance in the CFA Championship class beginning on February 6th, 2006.');
insert into item (CATEGORY_ID_FK, ID, NAME, DESCRIPTION) values('1','12','Maine Coon','The Maine Coon is one of the largest breeds of domestic cat, known for its intelligence and playfulness as well as its distinctive physical appearance. The breed is one of the oldest natural breeds in North America and originated from New England, making it America`s first indigenous show cat. The Maine Coon Cat is known as "the gentle giant."');
insert into item (CATEGORY_ID_FK, ID, NAME, DESCRIPTION) values('2','21','Beagle','The Beagle is a breed of medium-sized dog. A member of the hound group, it is similar in appearance to the Foxhound but smaller, with shorter legs and longer, softer ears. Beagles are scent hounds developed primarily for tracking hare, rabbit, and other game. They have a keen sense of smell and tracking instinct that often sees them employed as detection dogs for prohibited agricultural imports and foodstuffs in quarantine around the world. They are popular as pets because of their size, even temper, and lack of inherited health problems. These characteristics also make them the dog of choice for animal testing.');
insert into item (CATEGORY_ID_FK, ID, NAME, DESCRIPTION) values('2','22','Bullmastiff','The Bullmastiff is a powerful dog, said to be a cross between the English Mastiff and the Bulldog. Originally bred to find and immobilise poachers, the breed has proved its value as a family pet.');
insert into item (CATEGORY_ID_FK, ID, NAME, DESCRIPTION) values('2','23','German Shepherd','The German Shepherd Dog or Alsatian (see Breed names), is a popular breed of dog. German Shepherds are highly intelligent, agile and well-suited to active working environments. They are often deployed in various roles such as police work, guarding, search and rescue, therapy and in the military. They can also be found working as guide dogs for the blind. Despite their suitability for such work, German Shepherds can also make loyal and loving pets inside the home. They enjoy being around people and other animals, although socialization is critical for young puppies in order to prevent aggressive and dangerous behavior. German Shepherds are well-suited to obedience, with advanced and prestigious titles available to test both the handler and dog in various schutzhund trials.');
insert into item (CATEGORY_ID_FK, ID, NAME, DESCRIPTION) values('3','31','Boa','Boas are a type of snake that are members of the Boidae family. Boas are basal snakes that are "primitive" in evolutionary terms (i.e. less derived). They are constrictors and most give birth to live young. They have anal spurs, a pair of claws on each side of the cloaca which assist in mating. Boas are named after cows (Latin: bos) because of the old myth that boa snakes pursue cows and suckle them until they are drained to death.');
insert into item (CATEGORY_ID_FK, ID, NAME, DESCRIPTION) values('3','32','Snapping turtle','The Snapping Turtle (Chelydra serpentina), or more formally referred to as Common Snapping Turtle when distinguishing them from their larger cousins (Macrochelys), and are popularly nicknamed "snappers". They are large freshwater turtles of the family Chelydridae, ranging from southeastern Canada west to the Rocky Mountains (and beyond, where introduced), and south through Mexico to Ecuador.');
insert into item (CATEGORY_ID_FK, ID, NAME, DESCRIPTION) values('3','33','Leopard gecko','The leopard gecko gets its common name from the adult coloration of wild specimen, which is a cream to yellow ground color with black spots or stripes. However, selective breeding has produced many color morphs, including high yellow, tangerine, striped, patternless (no spots or stripes), lavender, blizzard (which are solid white or gray), and albino (no black pigments in markings).');