package spring.petstore.core.model;

// Generated Jul 30, 2007 12:22:19 PM by Hibernate Tools 3.2.0.beta8

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	// Fields    

	private long id;
	private Category category;
	private String name;
	private String description;

	// Constructors

	/** default constructor */
	public Item() {
	}

	/** minimal constructor */
	public Item(long id, Category category, String name) {
		this.id = id;
		this.category = category;
		this.name = name;
	}

	/** full constructor */
	public Item(long id, Category category, String name, String description) {
		this.id = id;
		this.category = category;
		this.name = name;
		this.description = description;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
